// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0fG4mn_VxKEd2oZotK6-rPd1x1lN7Q-Q',
    appId: '1:700792010765:web:26993d2778f1118c037d44',
    messagingSenderId: '700792010765',
    projectId: 'alerta-vuelos-49ba1',
    authDomain: 'alerta-vuelos-49ba1.firebaseapp.com',
    storageBucket: 'alerta-vuelos-49ba1.firebasestorage.app',
    measurementId: 'G-KKS6E5JK6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAkcbUdeUNbEeGm6TD5c6FDGO7hZGej1c',
    appId: '1:700792010765:android:517d9dffad214836037d44',
    messagingSenderId: '700792010765',
    projectId: 'alerta-vuelos-49ba1',
    storageBucket: 'alerta-vuelos-49ba1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArG20Y3cr1-dGWtjJ04VW5Gtg-J4XgOhg',
    appId: '1:700792010765:ios:fa8874170e44361d037d44',
    messagingSenderId: '700792010765',
    projectId: 'alerta-vuelos-49ba1',
    storageBucket: 'alerta-vuelos-49ba1.firebasestorage.app',
    iosBundleId: 'com.example.proyectoaerolineas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArG20Y3cr1-dGWtjJ04VW5Gtg-J4XgOhg',
    appId: '1:700792010765:ios:fa8874170e44361d037d44',
    messagingSenderId: '700792010765',
    projectId: 'alerta-vuelos-49ba1',
    storageBucket: 'alerta-vuelos-49ba1.firebasestorage.app',
    iosBundleId: 'com.example.proyectoaerolineas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0fG4mn_VxKEd2oZotK6-rPd1x1lN7Q-Q',
    appId: '1:700792010765:web:6e89f28d7d92822a037d44',
    messagingSenderId: '700792010765',
    projectId: 'alerta-vuelos-49ba1',
    authDomain: 'alerta-vuelos-49ba1.firebaseapp.com',
    storageBucket: 'alerta-vuelos-49ba1.firebasestorage.app',
    measurementId: 'G-DPTH7C63HM',
  );
}
